pipeline{
    agent{
        label 'docker-agent-local'
    }
    triggers{
        pollSCM('*/5 * * * *')
    }
    stages{
        stage('Test') {
            steps {
                dir('auth_service'){
                    sh './mvnw test'
                }
            }
        }
        stage('Build'){
            steps{
                dir('auth_service'){
                    sh './mvnw clean package -DskipTests'
                }
            }
        }
        stage('Deliver'){
            steps {
                script {
                    dir('auth_service'){
                        docker.build("auth_service:${env.BUILD_NUMBER}")
                    }
                }
            }
        }
        stage('Deploy Auth Service') {
            steps {
                sh '''
                docker rm -f auth_service || true
                docker run -d \
                    --name auth_service \
                    -p 8081:8080 \
                    auth_service:${env.BUILD_NUMBER}
                '''
            }
        }
    }
}