pipeline{
    agent{
        label 'docker-agent-local'
    }
    triggers{
        pollSCM('*/5 * * * *')
    }
    stages{
        stage('Test') {
            steps {
                dir('auth_service'){
                    sh './mvnw test'
                }
            }
        }
        stage('Build'){
            steps{
                dir('auth_service'){
                    sh './mvnw clean package'
                }
            }
        }
        stage('Deliver'){
            steps {
                script {
                    dir('auth_service'){
                        docker.build("auth_service:${env.BUILD_NUMBER}")
                    }
                }
            }
        }
    }
}